# Generated by `crucible create simple_mlp_on_mnist --kind job`. Feel free to edit.

import logging

from torchvision import datasets

from crucible.core.jobs import AbstractJob
from crucible.core.settings import MNIST_DATA_PATH


logger = logging.getLogger(__name__)


class Job(AbstractJob):
	"""Scaffolded job 'simple_mlp_on_mnist'."""

	def on_prepare(self) -> None:
		self.train_dataset = datasets.MNIST(root=MNIST_DATA_PATH, download=True, train=True)
		self.valid_dataset = datasets.MNIST(root=MNIST_DATA_PATH, download=True, train=False)

	def on_execute(self) -> dict[str, str]:
		logger.info(
			"Job 'simple_mlp_on_mnist' executed with train=%d valid=%d samples",
			len(self.train_dataset),
			len(self.valid_dataset),
		)
		return {"status": "ok", "job": "simple_mlp_on_mnist", "kind": "job"}


JOB_CLASS = Job
